package game;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/** This class holds all of the planes that will be generated by the FuturePlane class
 *
 */
public class Planes {
	private static int maxplanenumb = 10;
	static Random randomgen = new Random();
	private static double spawnThreshhold = 3000 + randomgen.nextInt(6000);
	private static double currTime = 0;
	
	/** This method holds all of the FuturePlanes in a list
	 * 
	 */
	public static ArrayList<Plane> planes;
	static {
		planes = new ArrayList<Plane>();
	}

	/** This method adds a plane to the list
	 * 
	 * @param p
	 */
	public static void add(Plane p) {
		planes.add(p);
	}

	/** This method removes a plane from the list
	 * 
	 * @param p
	 */
	public static void remove(Plane p) {
		planes.remove(p);
	}
	
	/** This method returns the number of planes in the list
	 * 
	 * @return
	 */
	public static int size(){
		return planes.size();
	}
	
	/** This method spawns planes on screen based on the time the game has already been running
	 *  and the number of planes already on screen
	 *  
	 * @param time
	 * @throws InterruptedException
	 */
	public static void updateTimer(double time) throws InterruptedException{
		currTime += time;
		if (currTime >= spawnThreshhold && planes.size() < maxplanenumb){
			new FuturePlane(randomgen.nextInt(60000));
			spawnThreshhold = 3000 + randomgen.nextInt(6000);
			currTime = 0;
		}
	}
	
}
